
CREATE TABLE reg (
    reg_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    reg_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    reg_email VARCHAR(255) UNIQUE NOT NULL,
    reg_verified BOOL NOT NULL DEFAULT FALSE
);
